<h1>Robin Mass Sender</h1>
<p>When you click the button, the process of sending your customers and orders will be pushed to the queue. The
    duration of this process depends on the amount of customers and orders in your system. Depending on your cron
    settings the Mass Send process will start. This process will send all customers and orders in batches to the
    ROBIN API. If you have logging turned on, you can see the process in var/log/Robinhq_Hooks.log
</p>